#spring.mail.host=smtp.163.com
#spring.mail.username=tornado4651@163.com
#spring.mail.password=Tornado4651
#spring.mail.default-encoding=utf-8
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/
#spring.datasource.username=root
#spring.datasource.password=18347176536=Ljf
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#

##thymeleaf
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=LEGACYHTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.cache=false


spring:
  mail:
    host: smtp.163.com
    username: tornado4651@163.com
    password: Tornado4651
    default-encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 18347176536=Ljf
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static