spring:
  mail:
    host: smtp.163.com #or others
    username: #your email
    password: #your password
    default-encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: #your password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static